version: '3.9'
services: 
    app_dev:
      build: .
      ports: 
        - 8080:8080
      volumes:
        - .:/usr/app/
      environment:
        FLASK_DEBUG: 1
        FLASK_ENV: development

    app_prod:
      build: .
      ports: 
        - 8080:8080
      environment:
        FLASK_DEBUG: 0
        FLASK_ENV: production

    pylint:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - .:/usr/app/
      entrypoint: ["/bin/bash", "-c", "pylint --rcfile=.pylintrc src tests | tee pylint.log"]
      working_dir: /usr/app/
      network_mode: none

    pytest:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - .:/usr/app/
      entrypoint: ["/bin/bash", "-c", "pytest"]
      working_dir: /usr/app/
      network_mode: none
